apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-app-deployment
  labels:
    app: flask-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-web-app
  template:
    metadata:
      labels:
        app: flask-web-app
    spec:
      containers:
      - name: flask-web-app-image
        image: avl4kul/flask-web-app:latest
        imagePullPolicy: Always
      nodeSelector:
        workerNode: "yes"
